import { calcNextGeneration } from './calcNextGeneration';
import { txt2Array } from './txt2Array';
import { array2Cells } from './array2Cells';

describe('calcNextGeneration', () => {
  let cells;
  let expectedCells;
  beforeEach(() => {
    cells = array2Cells(
      txt2Array(`
      ..........
      ...**.....
      ....*.....
      ..........
      ..........
      ...**.....
      ..**......
      .....*....
      ....*.....
      ..........
    `),
    );
    expectedCells = array2Cells(
      txt2Array(`
        ..........
        ...**.....
        ...**.....
        ..........
        ..........
        ..***.....
        ..**......
        ...**.....
        ..........
        ..........
      `),
    );
  });

  it('should return the next generation of cells', () => {
    const nextCells = calcNextGeneration(cells);
    expect(nextCells).toEqual(expectedCells);
  });
});
