import { getCellNeighbours } from './getCellNeighbours';
import { txt2Array } from './txt2Array';
import { array2Cells } from './array2Cells';

describe('getCellNeighbours', () => {
  let cells;

  beforeEach(() => {
    const startingGrid = txt2Array(`
      ..........
      ...**.....
      ....*.....
      ..........
      ..........
      ...**.....
      ..**......
      .....*....
      ....*.....
      ..........
    `);
    cells = array2Cells(startingGrid);
  });
  it('should return only the live neighbours for a cell', () => {
    expect(getCellNeighbours(cells, 4, 1).length).toBe(2);
    expect(getCellNeighbours(cells, 3, 6).length).toBe(3);
    expect(getCellNeighbours(cells, 4, 5).length).toBe(2);
  });
});
